### ISSUE TITLE
Internal UI Not Opening.

### ISSUE THREAD

**Issue by littlepriceonu** [L1ghtingBolt/BestSynapse#13]
I'm a scripter and I usually press **Insert** on my keyboard to open the internal UI and when I tried this on BestSynapse It doesn't seem to do anything at all. Trying this with normal synapse seems to work. I'm not sure if its another key or something along those lines but so far I'm unaware of any fix.

I've tried disabling and reenabling the Internal UI option but to no avail

**Comment by littlepriceonu** [comment]
Also when I try to use print statements it doesn't print to the roblox console?? And I'm sure its attached because the scripts in my autoexec folder executed

**Comment by L1ghtingBolt** [comment]
Try to turn it off and on in settings to update them

**Comment by littlepriceonu** [comment]
Thanks! Don't know why this didn't work before
