### ISSUE TITLE
using scrips

### ISSUE THREAD

**Issue by notab0t-creator** [L1ghtingBolt/BestSynapse#7]
please fix this if you can
[debug.log](https://github.com/L1ghtingBolt/BestSynapse/files/8393429/debug.log)
[logs.txt](https://github.com/L1ghtingBolt/BestSynapse/files/8393431/logs.txt)
when i attach then i use a script it says not attached but when i go to attach it it says already attached

**Comment by Notlsback** [comment]
this also happen to me

**Comment by L1ghtingBolt** [comment]
Happens to some people.
 If having issues with it not injecting/executing try to put this in your synapse x folder: 
[Download](https://anonfiles.com/32I8z3Rcx2/bs_bin_zip)
Unzip it at the synapse folder where you should have BestSynapse.

**Comment by L1ghtingBolt** [comment]
Added wontfix label because it's not fixable, is Synapse's fault. The fix I sent may not always work.
