### ISSUE TITLE
Text editor box is broken

### ISSUE THREAD

**Issue by yaukari2** [L1ghtingBolt/BestSynapse#8]
Simply nothing there, cant type or load saved scripts into it.

![image](https://user-images.githubusercontent.com/100224678/162059107-d0df08a5-a72e-41b1-b22b-4f1c3990babb.png)

**Comment by L1ghtingBolt** [comment]
Tryna delete editor_files inside bs_bin

**Comment by L1ghtingBolt** [comment]
Any updates?

**Comment by L1ghtingBolt** [comment]
Closing because there's no response, probably fixed in 1.7.
