### ISSUE TITLE
Clear Button not working

### ISSUE THREAD

**Issue by ghost** [L1ghtingBolt/BestSynapse#9]
I know it's a new Feature and I don't really need it but I noticed that it's called 'Settings' and whenever I click it my synapse just closes / crashes. 
If you need any log files please let me know and keep up the awesome work! 👍 
(So glad Better Synapse finally lets me type brackets and even has auto completion)

![image](https://user-images.githubusercontent.com/73931823/164981995-211f8b0f-b558-4048-bc3e-c184be771b0b.png)

Actually it seems that a lot isn't working right, just tryed to save a script and it also crashed.

**Comment by L1ghtingBolt** [comment]
Hey. Thanks for the feedback. I'll try to fix it tomorrow, I'm a bit sick right now.

**Comment by BingoIsaac** [comment]
Never fixed it?????????

**Comment by L1ghtingBolt** [comment]
> Never fixed it?????????

Finally fixed in v1.7. Sorry for being late.
